### PR TITLE
Remove inappropriate trademark usage

### PR DESCRIPTION
**Pull request by paularmstrong**
**Problem:** Trademark symbols are used in various documentation of this repository, but no trademark exists in the US Patent and Trademark office database 
**Solution:** Remove misleading and false trademarks.

### CODE REVIEW

**Comment by Myndex** [comment]
> **Problem:** Trademark symbols are used in various documentation of this repository, but no trademark exists in the US Patent and Trademark office database
> **Solution:** Remove misleading and false trademarks.

Hello @paularmstrong and thank you for your interest in APCA.

I am wondering if you wouldn't mind letting us know who or what prompted you to create this pull request? If you would like to respond to this query privately please feel free to email us at legal@myndex.com

Otherwise, I see you closed it shortly after making it, and I assume that you already determined what I'm going to clarify below:

There are no "false or misleading" trademarks listed here.

### I believe you are confusing ™ versus ®.

The symbol ™ does **_not_** require registration with the USPTO, it does nevertheless indicate the intention to legally protect the given trademark, and provide foundation thereof.

The symbol ® is the one that does require registration with the USPTO and cannot be used unless the trademark is in fact _"registered"_ and active. We are not using the ® symbol anywhere in this archive at this time, though we may in the future, pursuant to any final registered trademarks.


Thank you again,

Andy

**Comment by paularmstrong** [comment]
Yes, that was my mistake between ™ and ®. 

That being said, there is an abundance to the point of overuse of adding ™ to nearly everything in the documentation, which makes everything quite confusing and difficult to ascertain what is and is not important. eg “THE REVOLUTION WILL BE READABLE™”. What revolution? How does a revolution relate to this project? "Readability Contrast"™ (seems a bit vague), as well as every acronym. It would be helpful to determine which items are truly important to the project and should be trademarked vs what seems like just a random phrase.

**Comment by Myndex** [comment]
Hi @paularmstrong 

> *there is an abundance to the point of overuse*

Yes, this is currently in public beta, so handling IP protection is something that's under continuous review, and progressing. However the priorities are the primary research that is being conducted.

At the same time we're dealing with more than a couple harassing trolls and some of what you're mentioning relates to legal actions that have been or will need to be taken in some cases, particularly with people that are creating fraudulent versions with an apparent intent of obstructing the ongoing research and development process.

This is the first significant project I've personally launched as open-source, normally I work on closed projects, behind NDA, with others handling the IP. I wasn't quite ready for the "wild wild West" LOL

Thank you for your comments, they are taken into consideration.

**Comment by paularmstrong** [comment]
This all sounds really unfortunate. I'm so sorry for all of that! I've had a number of large open source repos, but never resulted in that kind of treatment,, so I can assure you it is not the norm.

Love the results of the algorithm. I'm throwing together a page that uses the apca-w3 package to read out Lc results with a bit of a different UI than the main site. Is there anything I need to be aware of outside of the bylines and disclaimers from the LICENSE?

**Comment by Myndex** [comment]
> *This all sounds really unfortunate. I'm so sorry for all of that! I've had a number of large open source repos, but never resulted in that kind of treatment,, so I can assure you it is not the norm.*

Yes it is very specific to this particular project because of the politics involved in accessibility and because this involves both breakthroughs and a paradigm shift in how human contrast perception of text is predicted. There are some very toxic individuals that we've had to deal with.

> *Love the results of the algorithm. I'm throwing together a page that uses the apca-w3 package to read out Lc results with a bit of a different UI than the main site. Is there anything I need to be aware of outside of the bylines and disclaimers from the LICENSE?*

Thank you, the document that describes conformance/compliance levels and requirements is @ the main SAPC-APCA repo, it is this document:

https://github.com/Myndex/SAPC-APCA/blob/master/documentation/minimum_compliance.md

Please let me know if you have any questions!

**Pull request closed without merging**
